// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sol.Data;

#nullable disable

namespace Sol.Migrations
{
    [DbContext(typeof(SolContext))]
    [Migration("20241112163124_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sol.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Animals", (string)null);
                });

            modelBuilder.Entity("Sol.Data.AnimalRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PredatorId")
                        .HasColumnType("int");

                    b.Property<int>("PreyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredatorId");

                    b.HasIndex("PreyId");

                    b.ToTable("AnimalRelation");
                });

            modelBuilder.Entity("Sol.Data.Human", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LeastFavoriteAnimalId")
                        .HasColumnType("int");

                    b.Property<int?>("MostFavoriteAnimalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeastFavoriteAnimalId");

                    b.HasIndex("MostFavoriteAnimalId");

                    b.ToTable("Humans", (string)null);
                });

            modelBuilder.Entity("Sol.Data.AnimalRelation", b =>
                {
                    b.HasOne("Sol.Data.Animal", null)
                        .WithMany()
                        .HasForeignKey("PredatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sol.Data.Animal", null)
                        .WithMany()
                        .HasForeignKey("PreyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sol.Data.Human", b =>
                {
                    b.HasOne("Sol.Data.Animal", null)
                        .WithMany()
                        .HasForeignKey("LeastFavoriteAnimalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sol.Data.Animal", null)
                        .WithMany()
                        .HasForeignKey("MostFavoriteAnimalId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
